global:
  scrape_interval: 15s
  external_labels:
    monitor: "codelab-monitor"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["env_alertmanager:9093"]

rule_files:
  - "/rules/*.yml"

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "alertmanager"
    scrape_interval: 5s
    static_configs:
      - targets: ["env_alertmanager:9093"]

  - job_name: "node"
    scrape_interval: 5s
    static_configs:
      - targets:
          - "172.19.16.9:9100"
        labels:
          instance: "zenkoo-01"
      - targets:
          - "172.19.16.16:9100"
        labels:
          instance: "zenkoo-02"

  - job_name: "traefik"
    scrape_interval: 5s
    static_configs:
      - targets: ["env_traefik:8082"]

  - job_name: "postgres"
    scrape_interval: 5s
    static_configs:
      - targets: ["runtime_postgres-exporter:9187"]

  - job_name: "consul"
    scrape_interval: 5s
    static_configs:
      - targets: ["runtime_consul-exporter:9107"]

  - job_name: "redis"
    scrape_interval: 5s
    static_configs:
      - targets: ["runtime_redis-exporter:9121"]

  - job_name: "memcached"
    scrape_interval: 5s
    static_configs:
      - targets: ["runtime_memcached-exporter:9150"]

  - job_name: "nats"
    scrape_interval: 5s
    static_configs:
      - targets: ["runtime_nats-exporter:7777"]
