global:
  scrape_interval: 15s
  external_labels:
    monitor: "codelab-monitor"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["env_alertmanager:9093"]

rule_files:
  - "/rules/*.yml"

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "alertmanager"
    scrape_interval: 5s
    static_configs:
      - targets: ["env_alertmanager:9093"]

  - job_name: "node"
    scrape_interval: 5s
    dns_sd_configs:
      - names:
        - 'tasks.env_node-exporter'
        type: 'A'
        port: 9100

  - job_name: "traefik"
    scrape_interval: 5s
    static_configs:
      - targets: ["env_traefik:8082"]
