server:
  http_listen_port: 3200

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
        http:
    jaeger:
      protocols:
        grpc:
        thrift_binary:
        thrift_compact:
        thrift_http:
    zipkin:
    opencensus:

query_frontend:
  search:
    duration_slo: 5s
    throughput_bytes_slo: 1.073741824e+09
  trace_by_id:
    duration_slo: 5s

ingester:
  max_block_duration: 5m

compactor:
  ring:
    kvstore:
  compaction:
    compaction_window: 1h

metrics_generator:

storage:
  trace:
    backend: local
    wal:
      path: /tmp/tempo/wal
    local:
      path: /tmp/tempo/blocks
    s3:
      bucket: tempo
      endpoint: env_minio
      region: hk-2
      insecure: true
      access_key: N6VJd3SmJmSWMeI91XTo
      secret_key: Hr6qXCjMhrIFebiXypYhG2u9IMxnDnUgYEWFNGqK

overrides:
  defaults:
    ingestion:
      rate_limit_bytes: 104857600
