version: "3.9"
services:
  # Nats (without jetstream)
  nats:
    image: nats:latest
    networks:
      - herewe-net
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 2s
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.nats.loadbalancer.server.port=8222"
        # HTTP
        - "traefik.http.routers.nats-http.rule=Host(`nats.env.zenkoo.herewe.tech`)"
        - "traefik.http.routers.nats-http.service=nats"
        - "traefik.http.routers.nats-http.entrypoints=web"
        # # HTTPS
        - "traefik.http.routers.nats-https.tls.certresolver=le"
        - "traefik.http.routers.nats-https.rule=Host(`nats.env.zenkoo.herewe.tech`)"
        - "traefik.http.routers.nats-https.service=nats"
        - "traefik.http.routers.nats-https.entrypoints=websecure"
        # Redirect
        - "traefik.http.routers.nats-http.middlewares=nats-redirectscheme"
        - "traefik.http.middlewares.nats-redirectscheme.redirectscheme.scheme=https"
        - "traefik.http.middlewares.nats-redirectscheme.redirectscheme.permanent=true"
        # Auth
        - "traefik.http.routers.nats-https.middlewares=nats-auth"
        - "traefik.http.middlewares.nats-auth.basicauth.users=herewe:$$apr1$$jLdnAN0h$$W7algjI5nCLeSUlyz9cu.0" # hello.herewe

  # Nats exporter
  nats-exporter:
    image: natsio/prometheus-nats-exporter:latest
    command: "http://runtime_nats:8222"
    networks:
      - herewe-net
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 2s
      restart_policy:
        condition: on-failure

  # Redis
  redis:
    image: redis:alpine
    volumes:
      - /data/zenkoo/storage/redis:/data
    networks:
      - herewe-net
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 2s
      restart_policy:
        condition: on-failure

  # Redis exporter
  redis-exporter:
    image: oliver006/redis_exporter:latest
    networks:
      - herewe-net
    environment:
      REDIS_ADDR: redis://runtime_redis:6379
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 2s
      restart_policy:
        condition: on-failure

  # Memcached
  memcached:
    image: memcached:alpine
    networks:
      - herewe-net
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 2s
      restart_policy:
        condition: on-failure

  # Memcached exporter
  memcached-exporter:
    image: prom/memcached-exporter:latest
    command: "--memcached.address=runtime_memcached:11211"
    networks:
      - herewe-net
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 2s
      restart_policy:
        condition: on-failure

  # Consul
  consul:
    image: hashicorp/consul:latest
    command: ["agent", "-server", "-ui", "-client", "0.0.0.0", "-bootstrap", "-bootstrap-expect", "1"]
    volumes:
      - /data/zenkoo/storage/consul/data:/consul/data
    networks:
      - herewe-net
    environment:
      CONSUL_BIND_INTERFACE: eth0
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 2s
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.consul.loadbalancer.server.port=8500"
        # HTTP
        - "traefik.http.routers.consul-http.rule=Host(`consul.env.zenkoo.herewe.tech`)"
        - "traefik.http.routers.consul-http.service=minio"
        - "traefik.http.routers.consul-http.entrypoints=web"
        # HTTPS
        - "traefik.http.routers.consul-https.tls.certresolver=le"
        - "traefik.http.routers.consul-https.rule=Host(`consul.env.zenkoo.herewe.tech`)"
        - "traefik.http.routers.consul-https.service=consul"
        - "traefik.http.routers.consul-https.entrypoints=websecure"
        # Redirect
        - "traefik.http.routers.consul-http.middlewares=consul-redirectscheme"
        - "traefik.http.middlewares.consul-redirectscheme.redirectscheme.scheme=https"
        - "traefik.http.middlewares.consul-redirectscheme.redirectscheme.permanent=true"
        # Auth
        - "traefik.http.routers.consul-https.middlewares=consul-auth"
        - "traefik.http.middlewares.consul-auth.basicauth.users=herewe:$$apr1$$jLdnAN0h$$W7algjI5nCLeSUlyz9cu.0" # hello.herewe

  # Consul exporter
  consul-exporter:
    image: prom/consul-exporter:latest
    command: "--consul.server=runtime_consul:8500"
    networks:
      - herewe-net
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 2s
      restart_policy:
        condition: on-failure

  # PostgreSQL exporter
  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:latest
    networks:
      - herewe-net
    environment:
      DATA_SOURCE_NAME: "postgres://postgres:hello.herewe@172.18.0.1:5432/postgres?sslmode=disable"
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 2s
      restart_policy:
        condition: on-failure

networks:
  herewe-net:
    external: true
