version: "3.9"
services:
  # BFFs
  svc_web_viewer:
    image: hkccr.ccs.tencentyun.com/zenkoo/svc.web.viewer:latest
    networks:
      - herewe-net
    environment:
      ZENKOO_CONFIG_CONSUL_ADDRESS: runtime_consul:8500
      ZENKOO_CONFIG_CONSUL_PREFIX: /zenkoo/config/svc.web.viewer
    volumes:
      - /data/zenkoo/logs/svc.web.viewer:/opt/zenkoo/logs
    deploy:
      mode: replicated
      update_config:
        parallelism: 1
        delay: 2s
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.svc_web_viewer.loadbalancer.server.port=9990"
        # HTTP
        - "traefik.http.routers.svc_web_viewer-http.rule=Host(`api.viewer.zenkoo.herewe.tech`)"
        - "traefik.http.routers.svc_web_viewer-http.service=svc_web_viewer"
        - "traefik.http.routers.svc_web_viewer-http.entrypoints=web"
        # # HTTPS
        - "traefik.http.routers.svc_web_viewer-https.tls.certresolver=le"
        - "traefik.http.routers.svc_web_viewer-https.rule=Host(`api.viewer.zenkoo.herewe.tech`)"
        - "traefik.http.routers.svc_web_viewer-https.service=svc_web_viewer"
        - "traefik.http.routers.svc_web_viewer-https.entrypoints=websecure"
        # Redirect
        - "traefik.http.routers.svc_web_viewer-http.middlewares=svc_web_viewer-redirectscheme"
        - "traefik.http.middlewares.svc_web_viewer-redirectscheme.redirectscheme.scheme=https"
        - "traefik.http.middlewares.svc_web_viewer-redirectscheme.redirectscheme.permanent=true"
    logging:
      driver: loki
      options:
        loki-url: "http://127.0.0.1:3100/loki/api/v1/push"

  svc_web_streamer:
    image: hkccr.ccs.tencentyun.com/zenkoo/svc.web.streamer:latest
    networks:
      - herewe-net
    environment:
      ZENKOO_CONFIG_CONSUL_ADDRESS: runtime_consul:8500
      ZENKOO_CONFIG_CONSUL_PREFIX: /zenkoo/config/svc.web.streamer
    volumes:
      - /data/zenkoo/logs/svc.web.streamer:/opt/zenkoo/logs
    deploy:
      mode: replicated
      update_config:
        parallelism: 1
        delay: 2s
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.svc_web_streamer.loadbalancer.server.port=9990"
        # HTTP
        - "traefik.http.routers.svc_web_streamer-http.rule=Host(`api.streamer.zenkoo.herewe.tech`)"
        - "traefik.http.routers.svc_web_streamer-http.service=svc_web_streamer"
        - "traefik.http.routers.svc_web_streamer-http.entrypoints=web"
        # # HTTPS
        - "traefik.http.routers.svc_web_streamer-https.tls.certresolver=le"
        - "traefik.http.routers.svc_web_streamer-https.rule=Host(`api.streamer.zenkoo.herewe.tech`)"
        - "traefik.http.routers.svc_web_streamer-https.service=svc_web_streamer"
        - "traefik.http.routers.svc_web_streamer-https.entrypoints=websecure"
        # Redirect
        - "traefik.http.routers.svc_web_streamer-http.middlewares=svc_web_streamer-redirectscheme"
        - "traefik.http.middlewares.svc_web_streamer-redirectscheme.redirectscheme.scheme=https"
        - "traefik.http.middlewares.svc_web_streamer-redirectscheme.redirectscheme.permanent=true"
    logging:
      driver: loki
      options:
        loki-url: "http://127.0.0.1:3100/loki/api/v1/push"

  svc_web_dashboard:
    image: hkccr.ccs.tencentyun.com/zenkoo/svc.web.dashboard:latest
    networks:
      - herewe-net
    environment:
      ZENKOO_CONFIG_CONSUL_ADDRESS: runtime_consul:8500
      ZENKOO_CONFIG_CONSUL_PREFIX: /zenkoo/config/svc.web.dashboard
    volumes:
      - /data/zenkoo/logs/svc.web.dashboard:/opt/zenkoo/logs
    deploy:
      mode: replicated
      update_config:
        parallelism: 1
        delay: 2s
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.svc_web_dashboard.loadbalancer.server.port=9990"
        # HTTP
        - "traefik.http.routers.svc_web_dashboard-http.rule=Host(`api.dashboard.zenkoo.herewe.tech`)"
        - "traefik.http.routers.svc_web_dashboard-http.service=svc_web_dashboard"
        - "traefik.http.routers.svc_web_dashboard-http.entrypoints=web"
        # # HTTPS
        - "traefik.http.routers.svc_web_dashboard-https.tls.certresolver=le"
        - "traefik.http.routers.svc_web_dashboard-https.rule=Host(`api.dashboard.zenkoo.herewe.tech`)"
        - "traefik.http.routers.svc_web_dashboard-https.service=svc_web_dashboard"
        - "traefik.http.routers.svc_web_dashboard-https.entrypoints=websecure"
        # Redirect
        - "traefik.http.routers.svc_web_dashboard-http.middlewares=svc_web_dashboard-redirectscheme"
        - "traefik.http.middlewares.svc_web_dashboard-redirectscheme.redirectscheme.scheme=https"
        - "traefik.http.middlewares.svc_web_dashboard-redirectscheme.redirectscheme.permanent=true"
    logging:
      driver: loki
      options:
        loki-url: "http://127.0.0.1:3100/loki/api/v1/push"

  # Micro services
  svc_infra_setting:
    image: hkccr.ccs.tencentyun.com/zenkoo/svc.infra.setting:latest
    networks:
      - herewe-net
    environment:
      ZENKOO_CONFIG_CONSUL_ADDRESS: runtime_consul:8500
      ZENKOO_CONFIG_CONSUL_PREFIX: /zenkoo/config/svc.infra.setting
    volumes:
      - /data/zenkoo/logs/svc.infra.setting:/opt/zenkoo/logs
    deploy:
      mode: replicated
      update_config:
        parallelism: 1
        delay: 2s
      restart_policy:
        condition: on-failure
    logging:
      driver: loki
      options:
        loki-url: "http://127.0.0.1:3100/loki/api/v1/push"

  svc_biz_account:
    image: hkccr.ccs.tencentyun.com/zenkoo/svc.biz.account:latest
    networks:
      - herewe-net
    environment:
      ZENKOO_CONFIG_CONSUL_ADDRESS: runtime_consul:8500
      ZENKOO_CONFIG_CONSUL_PREFIX: /zenkoo/config/svc.biz.account
    volumes:
      - /data/zenkoo/logs/svc.biz.account:/opt/zenkoo/logs
    deploy:
      mode: replicated
      update_config:
        parallelism: 1
        delay: 2s
      restart_policy:
        condition: on-failure
    logging:
      driver: loki
      options:
        loki-url: "http://127.0.0.1:3100/loki/api/v1/push"

  svc_biz_gift:
    image: hkccr.ccs.tencentyun.com/zenkoo/svc.biz.gift:latest
    networks:
      - herewe-net
    environment:
      ZENKOO_CONFIG_CONSUL_ADDRESS: runtime_consul:8500
      ZENKOO_CONFIG_CONSUL_PREFIX: /zenkoo/config/svc.biz.gift
    volumes:
      - /data/zenkoo/logs/svc.biz.gift:/opt/zenkoo/logs
    deploy:
      mode: replicated
      update_config:
        parallelism: 1
        delay: 2s
      restart_policy:
        condition: on-failure
    logging:
      driver: loki
      options:
        loki-url: "http://127.0.0.1:3100/loki/api/v1/push"


  svc_biz_room:
    image: hkccr.ccs.tencentyun.com/zenkoo/svc.biz.room:latest
    networks:
      - herewe-net
    environment:
      ZENKOO_CONFIG_CONSUL_ADDRESS: runtime_consul:8500
      ZENKOO_CONFIG_CONSUL_PREFIX: /zenkoo/config/svc.biz.room
    volumes:
      - /data/zenkoo/logs/svc.biz.room:/opt/zenkoo/logs
    deploy:
      mode: replicated
      update_config:
        parallelism: 1
        delay: 2s
      restart_policy:
        condition: on-failure
    logging:
      driver: loki
      options:
        loki-url: "http://127.0.0.1:3100/loki/api/v1/push"
networks:
  herewe-net:
    external: true
